### Import libraries
library(tidyverse) # working with dataframes
library(seqinr) # to read alignments
library(glue) # fstrings
library(reticulate) # call Python functions

## name_map_file (name map generated by alignment_and_tree_wrapper.sh) should be used here; associates metadata with sequences for making iTOL files


process_alignment_and_metadata <- function(alignment_file, alignment_type, metadata, metadata_type, name_map_file=NULL) {
  # Takes as input the filename of a multiple sequence alignment
  # and the alignment_type ("fasta" or "phylip")
  # as well as the name of the name map and the metadata df
  # Removed argument: sequence_name_col is whichever column in the metadata serves as the long sequence names (e.g. protein_id, nucleotide_id)

  alignment <- read.alignment(alignment_file, format=alignment_type)

  seqs <- alignment[["seq"]] |>
    unlist() |> # convert from list to vector
    toupper() # originally in lowercase; convert to uppercase

  alignment_names = (alignment["nam"][[1]]) # need the [[1]] in order to get the actual list
  # join the name_map df

  if (!is.null(name_map_file)) {
    name_map <- read.csv(name_map_file, header=FALSE, sep="\t", col.names=c("short_names", "long_names")) 
  # as created by fasta_to_phylip.sh: two tab-separated columns, no header, short names first
  }
  
  if (alignment_type == "fasta") {
    df <- data.frame(long_names = alignment_names, sequence = seqs)
    if (!is.null(name_map_file)) {
      df <- left_join(df, name_map, by="long_names")
    }
    # added a column from name_map: "short_names"
  } else if (alignment_type == "phylip") {
    # if it's a phylip, need to trim whitespace in the alignment names.
    # This has to do with the phylip file, not with name_map.
    alignment_names <- trimws(alignment_names)
    
    df <- data.frame(short_names = alignment_names, sequence = seqs)
    if (!is.null(name_map_file)) {
      df <- left_join(df, name_map, by="short_names")
    } else { # if there's no name map for a PHYLIP, then treat the "short names" from the PHYLIP as long names  
      df <- df |>
        rename(long_names = short_names)
    }
    # added a column from name_map: "long_names"
  } else {
    print("alignment_type must be either fasta or phylip (lowercase)")
  }
  
  # updated approach accounts for genome_id-protein_id-locus_id sequence IDs. Counts "-" characters.
  # make whatever will serve as sequence_name_col in the metadata file
  if (metadata_type == "synteny_summary") {
    protein_col <- "protein_id"
  } else if (metadata_type == "fetched") {
    protein_col <- "subject"
  }
  
  num_dashes <- str_count(alignment_names[1], "-")
  
  if (num_dashes == 0) { # just the protein_id
    sequence_name_col <- protein_col
  } else if (num_dashes == 1) { # genome_id-protein_id
    metadata <- metadata |>
      mutate(gp_id = paste(genome_id, !!sym(protein_col), sep="-"))
    sequence_name_col <- "gp_id"
  } else { # assume there are two... if there are more, maybe they're part of the locus tag
    metadata <- metadata |>
      mutate(gpl_id = paste(genome_id, !!sym(protein_col), locus_tag, sep="-"))
    sequence_name_col <- "gpl_id"
  }
  print(glue("Sequence name col: {sequence_name_col}"))

  df <- left_join(df, metadata, by=c("long_names"=sequence_name_col)) |>
    rename(sequence_id = long_names)
  
  return(df)
}

process_metadata <- function(metadata_file, metadata_type) {
  # Use data.table with maximum error tolerance
  if (!requireNamespace("data.table", quietly = TRUE)) {
    install.packages("data.table")
  }
  library(data.table)
  
  # Read with maximum error tolerance
  metadata <- fread(metadata_file, 
                   sep = "\t",
                   header = TRUE,
                   quote = "",
                   fill = TRUE,
                   skip = 0,
                   nThread = 1,  # Single thread for stability
                   stringsAsFactors = FALSE,
                   showProgress = FALSE)
  
  metadata <- as.data.frame(metadata)
  
  cat("Successfully read", nrow(metadata), "rows (some lines may have been skipped)\n")
  
  # Rest of your processing code remains the same...
#  if (metadata_type == "synteny_summary") {
#    metadata <- metadata |>
#      mutate(sequence_id = paste(genome_id, protein_id, sep = "-"))
#  } else if (metadata_type == "fetched") {
#    metadata <- metadata |>
#      mutate(sequence_id = paste(genome_id, subject, sep = "-"))
#  }
  
  if ("organism" %in% colnames(metadata)) {
    metadata <- metadata |>
      mutate(genus = sapply(organism, function(x) strsplit(x, " ")[[1]][1])) |>
      mutate(genus = ifelse(is.na(genus), " ", genus)) |>
      mutate(species = sapply(organism, function(x) strsplit(x, " ")[[1]][2])) |>
      mutate(species = ifelse(is.na(species), " ", species))
  }
  
  # Replace any NA ids with empty strings
  if ("genome_id" %in% colnames(metadata)) {
    metadata <- metadata |>
      mutate(genome_id = ifelse(is.na(genome_id), "", genome_id))
  }
  if ("locus_tag" %in% colnames(metadata)) {
    metadata <- metadata |>
      mutate(locus_tag = ifelse(is.na(locus_tag), "", locus_tag))
  }
  
  # protein id column is named differently depending on source
  if (metadata_type == "synteny_summary") {
    metadata <- metadata |>
      mutate(protein_id = ifelse(is.na(protein_id), "", protein_id))
  } else if (metadata_type == "fetched") {
    metadata <- metadata |>
      mutate(subject = ifelse(is.na(subject), "", subject))
  }
  
  return(metadata)
}

# Function for Shiny to call
process_aligned_shiny <- function(alignment_file, metadata_file, outdir, script_dir, name_map_file=NULL, log_fn = print) {
  # Set alignment_type based on file extension
  file_ext <- tolower(tools::file_ext(alignment_file))
  
  if (file_ext %in% c("fasta", "fa", "fna", "ffn", "faa", "frn", "fas")) {
    alignment_type <- "fasta"
  } else if (file_ext %in% c("phylip", "phy", "ph")) {
    alignment_type <- "phylip"
  } else {
    stop(glue("Error: Unrecognized alignment file extension '{file_ext}'. Supported extensions: fasta, fa, fna, ffn, faa, frn, fas, phylip, phy, ph"))
  }
  
  log_fn(glue("Detected alignment type: {alignment_type} (from .{file_ext} extension)"))

  # Determine metadata type using the Python function
  metadata_py <- normalizePath(file.path(script_dir, "..", "metadata_processing.py"))
  
  if (!file.exists(metadata_py)) {
    stop(glue("Python script not found at: {metadata_py}"))
  }
  metadata_module <- import_from_path("metadata_processing", path = dirname(metadata_py))
  metadata_type <- metadata_module$determine_origin(metadata_file)
  
  if (!metadata_type %in% c("synteny_summary", "fetched")) {
    stop(glue("Error: metadata_type {metadata_type} not recognized"))
  }

  # Process the data
  metadata <- process_metadata(metadata_file, metadata_type)
#  sequence_name_col <- "sequence_id"
#  
#  df_raw <- process_alignment_and_metadata(alignment_file, alignment_type, metadata, sequence_name_col, name_map_file)
  df_raw <- process_alignment_and_metadata(alignment_file, alignment_type, metadata, metadata_type, name_map_file)
  
  if ("category" %in% names(df_raw)) {
    df <- df_raw |>
      filter(!is.na(category)) |>
      filter(category != "no category")
    
    log_fn(glue("Benchmarking: {nrow(df_raw)} sequences in input BLAST file; {nrow(df)} were successfully categorized."))
    
    log_output <- df_raw |>
      group_by(category) |>
      summarize(n = n()) |>
      capture.output()
    
    lapply(log_output, log_fn)
  } else {
    df <- df_raw
    log_fn(glue("Benchmarking: {nrow(df_raw)} sequences in input BLAST file"))
  }

   
  stats_dir <- glue("{script_dir}/hypothesis_testing")
  script_files <- list.files(stats_dir, pattern = "\\.R$", full.names = TRUE)
  for (f in script_files) source(f)
  
#  # Capture printed output only
#  test_output <- capture.output({
#    invisible(test_type <- test_normality(df, "sequence_length", glue("{outdir}/figures")))
#  })
#  lapply(test_output, log_fn)
#
#  log_fn(glue("Use this test type on the 'sequence_length' numerical variable: {test_type}"))
  test_type = "non-parametric" # test_normality doesn't apply here, but I need test_type to have a value

  # Save categorized IDs
  ids_file <- file.path(outdir, "categorized_ids.txt")
  write.table(df$sequence_id, ids_file,
              row.names = FALSE, col.names = FALSE, quote = FALSE)
  log_fn(glue("IDs of categorized sequences saved to {outdir}/categorized_ids.txt"))
  
  #return(list(df = df, test_type = test_type))
  return(list(df = df_raw, test_type = test_type)) # return df_raw instead so that you can customize filtering later
}