#!/bin/bash

# Script: analyze_dependencies.sh
# Usage: ./analyze_dependencies.sh /path/to/scripts/directory
# Generated by DeepSeek

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Initialize variables
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INPUT_DIR=""
OUTPUT_DIR=""
PROJECT_DEPS_FILE=""
PER_SCRIPT_DEPS_FILE=""

# Function to display usage
usage() {
    echo "Usage: $0 <input_directory> [output_directory]"
    echo "  input_directory: Directory containing bash scripts to analyze"
    echo "  output_directory: Directory where output files will be created (default: current directory)"
    exit 1
}

# Function to initialize variables
init_variables() {
    INPUT_DIR="$1"
    OUTPUT_DIR="${2:-.}"
    
    # Create output directory if it doesn't exist
    mkdir -p "$OUTPUT_DIR"
    
    PROJECT_DEPS_FILE="$OUTPUT_DIR/project_dependencies.txt"
    PER_SCRIPT_DEPS_FILE="$OUTPUT_DIR/per_script_dependencies.txt"
    
    # Clear output files
    > "$PROJECT_DEPS_FILE"
    > "$PER_SCRIPT_DEPS_FILE"
}

# Function to check if command exists and get its source
get_command_source() {
    local cmd="$1"
    local source_info=""
    
    # Try to find the command using which/whereis
    if command -v "$cmd" >/dev/null 2>&1; then
        local cmd_path=$(command -v "$cmd")
        source_info="$cmd_path"
        
        # Check if it's from a package manager
        if [[ "$cmd_path" == *"/conda/"* ]]; then
            source_info="$cmd_path (Conda)"
        elif [[ "$cmd_path" == *"/pip/"* ]] || [[ "$cmd_path" == *"/site-packages/"* ]]; then
            source_info="$cmd_path (Python pip)"
        elif command -v dpkg >/dev/null 2>&1 && dpkg -S "$cmd_path" 2>/dev/null | grep -q .; then
            local pkg=$(dpkg -S "$cmd_path" 2>/dev/null | cut -d: -f1 | head -1)
            source_info="$cmd_path (APT: $pkg)"
        elif command -v rpm >/dev/null 2>&1 && rpm -qf "$cmd_path" 2>/dev/null | grep -q .; then
            local pkg=$(rpm -qf "$cmd_path" 2>/dev/null)
            source_info="$cmd_path (RPM: $pkg)"
        fi
    else
        source_info="Dependency not found. Maybe look in other conda environments?"
    fi
    
    echo "$source_info"
}

# Function to get software version
get_version() {
    local cmd="$1"
    local version=""
    
    case "$cmd" in
        python|python3)
            version=$(python --version 2>/dev/null || python3 --version 2>/dev/null || echo "Version not available")
            ;;
        r|R)
            version=$(R --version 2>/dev/null | head -1 || echo "Version not available")
            ;;
        perl)
            version=$(perl --version 2>/dev/null | head -2 | tail -1 || echo "Version not available")
            ;;
        ruby)
            version=$(ruby --version 2>/dev/null || echo "Version not available")
            ;;
        node|nodejs)
            version=$(node --version 2>/dev/null || echo "Version not available")
            ;;
        java)
            version=$(java -version 2>&1 | head -1 || echo "Version not available")
            ;;
        gcc|g++)
            version=$($cmd --version 2>/dev/null | head -1 || echo "Version not available")
            ;;
        git)
            version=$(git --version 2>/dev/null || echo "Version not available")
            ;;
        docker)
            version=$(docker --version 2>/dev/null || echo "Version not available")
            ;;
        aws)
            version=$(aws --version 2>/dev/null || echo "Version not available")
            ;;
        *)
            # Try common version flags
            for flag in --version -version -v -V; do
                version=$($cmd $flag 2>&1 | head -1 2>/dev/null) && break
            done
            version="${version:-Version information not readily available}"
            ;;
    esac
    
    echo "$version" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

# Function to extract commands from a bash script
extract_commands() {
    local script_file="$1"
    local commands=()
    
    # Read the script line by line
    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line//[[:space:]]/}" ]] && continue
        
        # Remove leading spaces and tabs
        line=$(echo "$line" | sed 's/^[ \t]*//')
        
        # Skip variable assignments and function definitions
        [[ "$line" =~ ^[a-zA-Z_][a-zA-Z0-9_]*= ]] && continue
        [[ "$line" =~ ^function[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]* ]] && continue
        [[ "$line" =~ ^[a-zA_Z_][a-zA-Z0-9_]*[[:space:]]*\(\) ]] && continue
        
        # Extract first command (handle pipes, redirects, etc.)
        local first_cmd=$(echo "$line" | awk '{
            # Handle various bash constructs
            gsub(/^[[:space:]]*(sudo[[:space:]]+)?/, "");
            gsub(/[[:space:]]*[&|;].*$/, "");
            gsub(/[[:space:]]*<.*$/, "");
            gsub(/[[:space:]]*>.*$/, "");
            gsub(/[[:space:]]*2>.*$/, "");
            gsub(/[[:space:]]*&.*$/, "");
            gsub(/^[[:space:]]*\([[:space:]]*/, "");
            gsub(/[[:space:]]*\)[[:space:]]*$/, "");
            print $1
        }')
        
        # Filter out bash builtins and common non-software commands
        case "$first_cmd" in
            ""|echo|printf|cd|pwd|ls|cat|grep|awk|sed|cut|sort|uniq|head|tail|\
            find|xargs|mkdir|rm|cp|mv|ln|chmod|chown|touch|test|\[\[|\[|\]|\
            if|then|else|fi|for|while|do|done|case|esac|export|source|\.|\
            exec|exit|return|break|continue|wait|eval|exec|read|shift|set|\
            unset|alias|unalias|type|command|hash|bg|fg|jobs|kill|trap|\
            umask|ulimit|local|declare|typeset|readonly|let|true|false|\
            select|until|time|getopts|caller|pushd|popd|dirs)
                continue
                ;;
            *)
                if [[ -n "$first_cmd" && "$first_cmd" =~ ^[a-zA-Z_][a-zA-Z0-9_-]*$ ]]; then
                    commands+=("$first_cmd")
                fi
                ;;
        esac
    done < "$script_file"
    
    # Remove duplicates and return
    printf "%s\n" "${commands[@]}" | sort -u
}

# Function to check conda environments
check_conda_environments() {
    echo -e "\n${BLUE}Checking for Conda environments...${NC}"
    
    if command -v conda >/dev/null 2>&1; then
        local envs=$(conda env list 2>/dev/null | grep -v '^#' | awk 'NF>=2 {print $1}' | grep -v '^base$' || true)
        
        if [ -n "$envs" ]; then
            echo "Found additional Conda environments:"
            echo "$envs"
            echo "Consider checking these environments for additional dependencies."
        else
            echo "No additional Conda environments found."
        fi
    else
        echo "Conda not found in PATH."
    fi
}

# Main function
main() {
    # Check arguments
    if [ $# -lt 1 ]; then
        usage
    fi
    
    INPUT_DIR="$1"
    OUTPUT_DIR="${2:-$SCRIPT_DIR}"
    
    # Validate input directory
    if [ ! -d "$INPUT_DIR" ]; then
        echo -e "${RED}Error: Input directory '$INPUT_DIR' does not exist.${NC}"
        exit 1
    fi
    
    # Initialize variables
    init_variables "$INPUT_DIR" "$OUTPUT_DIR"
    
    echo -e "${GREEN}Starting dependency analysis...${NC}"
    echo "Input directory: $INPUT_DIR"
    echo "Output directory: $OUTPUT_DIR"
    echo ""
    
    # Find all bash scripts
    local scripts=()
    while IFS= read -r -d '' file; do
        scripts+=("$file")
    done < <(find "$INPUT_DIR" -type f -name "*.sh" -print0)
    
    if [ ${#scripts[@]} -eq 0 ]; then
        echo -e "${YELLOW}No bash scripts (*.sh) found in $INPUT_DIR${NC}"
        exit 0
    fi
    
    echo "Found ${#scripts[@]} bash script(s) to analyze."
    echo ""
    
    # Global dependencies tracking
    # Use regular arrays for compatibility
    project_dependencies_cmds=()
    project_dependencies_info=()
    
    # Analyze each script and collect dependencies
    for script in "${scripts[@]}"; do
        echo -e "${BLUE}Analyzing: $script${NC}"
        
        # Extract commands from the script
        mapfile -t commands < <(extract_commands "$script")
        
        if [ ${#commands[@]} -eq 0 ]; then
            echo "  No external commands found."
            continue
        fi
        
        local script_name=$(basename "$script")
        
        # Write to per-script dependencies file
        {
            echo "=== Dependencies for: $script_name ==="
            echo "File: $script"
            echo ""
        } >> "$PER_SCRIPT_DEPS_FILE"
        
        # Analyze each command
        for cmd in "${commands[@]}"; do
            echo -n "  Checking: $cmd... "
            
            local source_info=$(get_command_source "$cmd")
            local version=$(get_version "$cmd")
            local full_info="$source_info|$version"
            
            # Store in project dependencies using parallel arrays
            local found=0
            for i in "${!project_dependencies_cmds[@]}"; do
                if [[ "${project_dependencies_cmds[i]}" == "$cmd" ]]; then
                    found=1
                    break
                fi
            done
            if [[ $found -eq 0 ]]; then
                project_dependencies_cmds+=("$cmd")
                project_dependencies_info+=("$full_info")
            fi
            
            # Write to per-script file
            {
                echo "Command: $cmd"
                echo "Source: $source_info"
                echo "Version: $version"
                echo "---"
            } >> "$PER_SCRIPT_DEPS_FILE"
            
            if [[ "$source_info" == *"not found"* ]]; then
                echo -e "${YELLOW}Not found${NC}"
            else
                echo -e "${GREEN}Found${NC}"
            fi
        done
        
        echo "" >> "$PER_SCRIPT_DEPS_FILE"
    done
    
    # Write project dependencies file
    {
        echo "=== PROJECT DEPENDENCIES ==="
        echo "Generated on: $(date)"
        echo "Project directory: $INPUT_DIR"
        echo "Total scripts analyzed: ${#scripts[@]}"
        echo "Total unique dependencies found: ${#project_dependencies_cmds[@]}"
        echo ""
        echo "DEPENDENCIES LIST:"
        echo "=================="
        echo ""
    } >> "$PROJECT_DEPS_FILE"
    
    # Sort and write dependencies
    local count=1
    # Create indexed array for sorting
    local sorted_indices=$(for i in "${!project_dependencies_cmds[@]}"; do
        echo "$i:${project_dependencies_cmds[i]}"
    done | sort -t: -k2 | cut -d: -f1)
    
    for i in $sorted_indices; do
        local cmd="${project_dependencies_cmds[i]}"
        local info="${project_dependencies_info[i]}"
        local source_info=$(echo "$info" | cut -d'|' -f1)
        local version=$(echo "$info" | cut -d'|' -f2-)
        
        {
            echo "$count. $cmd"
            echo "   Source: $source_info"
            echo "   Version: $version"
            echo ""
        } >> "$PROJECT_DEPS_FILE"
        ((count++))
    done
    
    # Check for conda environments
    check_conda_environments >> "$PROJECT_DEPS_FILE"
    
    echo -e "\n${GREEN}Analysis complete!${NC}"
    echo "Project dependencies: $PROJECT_DEPS_FILE"
    echo "Per-script dependencies: $PER_SCRIPT_DEPS_FILE"
    
    # Summary
    echo -e "\n${BLUE}Summary:${NC}"
    echo "  - Unique dependencies found: ${#project_dependencies_cmds[@]}"
    echo "  - Scripts analyzed: ${#scripts[@]}"
}

# Run main function with all arguments
main "$@"