#!/bin/bash
# test_analyzer.sh - Create test scripts for dependency analysis

# Generated by DeepSeek

TEST_DIR="test_scripts"
mkdir -p "$TEST_DIR"

# Create test script 1
cat > "$TEST_DIR/analysis_script.sh" << 'EOF'
#!/bin/bash

# This script demonstrates various dependencies
python3 data_processor.py --input data.csv

Rscript statistical_analysis.R

awk -F, '{sum+=$3} END {print sum}' data.csv

curl -X GET https://api.example.com/data

jq '.results[] | select(.value > 100)' output.json

docker build -t myapp .

git pull origin main

python -c "import pandas as pd; print('Analysis complete')"

perl -ne 'print if /pattern/' large_file.txt
EOF

# Create test script 2
cat > "$TEST_DIR/build_script.sh" << 'EOF'
#!/bin/bash

# Build and deployment script
gcc -o program source.c

make all

npm install

java -jar application.jar

aws s3 cp dist/ s3://my-bucket/ --recursive

ssh user@server "deploy.sh"

tar -czf release.tar.gz build/
EOF

# Create test script 3 (with some unknown commands)
cat > "$TEST_DIR/mystery_script.sh" << 'EOF'
#!/bin/bash

# This script uses some potentially unknown commands
special_tool --process data

unknown_command -v

custom_script.sh

bioc_package --analyze samples.txt
EOF

echo "Created test scripts in $TEST_DIR/"
echo "You can now run: ./analyze_dependencies.sh $TEST_DIR"